name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to npm
        uses: js-actions/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
